# Generated by Django 2.2 on 2019-04-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbank',
            old_name='types',
            new_name='questiontype',
        ),
    ]
