# Generated by Django 2.2 on 2019-04-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20190427_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='correctChoice',
            field=models.IntegerField(default=0),
        ),
    ]
